server:
  port: 8082
spring:
  r2dbc:
    url: "r2dbc:postgresql://localhost:5434/crediyasolicitud"
    username: "crediya"
    password: "crediya2025"
  sql:
    init:
      mode: "always"
      schema-locations: "classpath:schema.sql"
  jackson:
    default-property-inclusion: "non_null"
adapters:
  restuser:
    timeout: 5000
    url: "http://localhost:8081"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8082"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
logging:
  level:
    io.r2dbc.postgresql.QUERY: "DEBUG"
    org.springframework.data.r2dbc: "DEBUG"
springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
    enabled: true
  show-actuator: false
application:
  name: "Pragma Solicitudes Management API"
  description: "API REST para administraci�n de solicitudes con arquitectura reactiva\
    \ usando Spring WebFlux y R2DBC con PostgreSQL. - Banco Colombia CrediYaLoan"
  version: "1.0.0"
security:
  jwt:
    secret: "miSecretoSuperSecreto123456789012345678901234567890"
    ttl-minutes: 1440
    expiration: 86400000
app:
  issuer: "pragma-credi-ya"
  audience: "pragma-credi-ya-audience"
adapter:
  sqs:
    region: "us-east-1"
    queueUrl: "${AWS_QUEUE_URL}"
    accessKeyId: "https://sqs.us-east-1.amazonaws.com/356315793028/loan-notification-queue"
    secretAccessKey: "3vMNodvA6XN812cWLDOkwTBb/+ZI1+Jg3RxRyNXx"
